### ISSUE TITLE
invalid stream error

### ISSUE THREAD

**Issue by Ashu225371** [jksinghpro/spark-jms#1]
I am getting error while reading stream as 
Exception in thread "main" com.rabbitmq.jms.util.RMQJMSException: invalid stream header: 48656C6C
        at com.rabbitmq.jms.client.RMQMessage.fromMessage(RMQMessage.java:1128)
        at com.rabbitmq.jms.client.RMQMessage.convertJmsMessage(RMQMessage.java:901)
        at com.rabbitmq.jms.client.RMQMessage.convertMessage(RMQMessage.java:895)
        at com.rabbitmq.jms.client.RMQMessageConsumer.receive(RMQMessageConsumer.java:354)
        at com.rabbitmq.jms.client.RMQMessageConsumer.receive(RMQMessageConsumer.java:268)
        at jk.bigdata.tech.jms.JmsDatasourceRelation.buildScan(JmsDataSourceRelation.scala:39)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:308)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
        at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)

**Comment by adamlukaszewski** [comment]
Me too.  Have you somehow resolved the issue? 

Thanks and best regards,
Adam L.
